const state={goal:'gain',filter:'背',equipment:'全部',exerciseType:'全部',exerciseLimit:60,selectedTrainingDay:0,completedByDay:{},profile:{age:28,height:175,weight:72,sex:'male',activity:1.375},completed:new Set()};
const titles={home:'首页',training:'训练计划',exercise:'动作库',diet:'饮食计划',profile:'我的'};
const demoExercises=[
 {id:1,name:'杠铃卧推',part:'胸',equipment:'杠铃',target:'胸大肌',icon:'推',steps:['双脚踩稳地面，肩胛骨向后下方收紧。','握距略宽于肩，控制杠铃下降至胸部中下方。','保持手腕中立，向上推起并呼气。']},
 {id:2,name:'哑铃上斜卧推',part:'胸',equipment:'哑铃',target:'上胸',icon:'推',steps:['训练凳调整至约30度。','肩胛稳定，哑铃下降到胸部两侧。','沿自然弧线推起，不碰撞哑铃。']},
 {id:3,name:'高位下拉',part:'背',equipment:'器械',target:'背阔肌',icon:'拉',steps:['挺胸坐稳，双手略宽于肩。','肘部向身体两侧下拉，横杆靠近上胸。','缓慢还原，避免借助身体后仰。']},
 {id:4,name:'坐姿划船',part:'背',equipment:'器械',target:'中背',icon:'拉',steps:['脊柱保持中立，胸部自然打开。','肘部贴近身体向后拉，肩胛骨靠拢。','控制手柄前移，不要含胸耸肩。']},
 {id:5,name:'高脚杯深蹲',part:'腿',equipment:'哑铃',target:'股四头肌',icon:'蹲',steps:['将哑铃置于胸前，双脚略宽于肩。','膝盖与脚尖方向一致，臀部向后下蹲。','脚掌均匀发力站起，保持躯干稳定。']},
 {id:6,name:'罗马尼亚硬拉',part:'腿',equipment:'哑铃',target:'腘绳肌',icon:'髋',steps:['双膝微屈，哑铃靠近腿部。','臀部向后移动，保持背部中立。','感受大腿后侧拉伸后收紧臀部站起。']},
 {id:7,name:'哑铃肩推',part:'肩',equipment:'哑铃',target:'三角肌',icon:'举',steps:['收紧核心，哑铃位于肩部两侧。','向上推至手臂接近伸直。','控制下放，避免腰部过度反弓。']},
 {id:8,name:'哑铃侧平举',part:'肩',equipment:'哑铃',target:'三角肌中束',icon:'展',steps:['手肘微屈，肩膀下沉。','向身体两侧抬起至接近肩高。','使用可控重量，避免摆动借力。']},
 {id:9,name:'哑铃弯举',part:'手臂',equipment:'哑铃',target:'肱二头肌',icon:'屈',steps:['上臂贴近身体，手腕保持中立。','弯曲肘部举起哑铃。','缓慢下放，不用身体摆动。']},
 {id:10,name:'绳索下压',part:'手臂',equipment:'器械',target:'肱三头肌',icon:'压',steps:['肘部固定在身体两侧。','向下伸展肘部，末端分开绳索。','控制还原，肩膀保持稳定。']},
 {id:11,name:'平板支撑',part:'核心',equipment:'徒手',target:'腹部核心',icon:'撑',steps:['肘部置于肩膀正下方。','收紧腹部和臀部，身体保持直线。','正常呼吸，腰部不下沉。']},
 {id:12,name:'死虫式',part:'核心',equipment:'徒手',target:'深层核心',icon:'稳',steps:['仰卧抬腿，髋膝约90度。','腰背贴地，对侧手脚缓慢伸展。','保持核心收紧后返回并换边。']},
 {id:13,name:'辅助引体向上',part:'背',equipment:'器械',target:'背阔肌',icon:'拉',steps:['选择合适辅助重量，双手握住横杆。','肩胛先下沉，再将胸口拉向横杆。','控制下降至手臂伸展，避免摆动。']},
 {id:14,name:'反握高位下拉',part:'背',equipment:'器械',target:'背阔肌下部',icon:'拉',steps:['掌心朝向自己，握距与肩同宽。','挺胸并将肘部向下向后拉。','缓慢还原，保持躯干稳定。']},
 {id:15,name:'杠铃俯身划船',part:'背',equipment:'杠铃',target:'中背',icon:'划',steps:['髋部后移，保持脊柱中立。','将杠铃拉向腹部，肩胛骨靠拢。','控制下放，避免腰背代偿。']},
 {id:16,name:'单臂哑铃划船',part:'背',equipment:'哑铃',target:'背阔肌',icon:'划',steps:['一手一膝支撑，躯干稳定。','肘部贴近身体将哑铃拉向髋部。','缓慢伸展手臂，避免身体旋转。']}
];
const exercises=window.REAL_EXERCISES||window.OPEN_EXERCISES||demoExercises;
const workoutLibraryMap={
 '杠铃卧推':'0025','哑铃上斜卧推':'0314','俯卧撑':'0662',
 '高位下拉':'2330','杠铃俯身划船':'0027','坐姿划船':'0861','单臂哑铃划船':'0292',
 '高脚杯深蹲':'1760','罗马尼亚硬拉':'1459','保加利亚分腿蹲':'0336','站姿提踵':'1373',
 '哑铃肩推':'0405','哑铃侧平举':'0334','绳索面拉':'0178',
 '哑铃弯举':'0285','绳索下压':'0241','锤式弯举':'0313','平板支撑':'0464'
};
const weeklyWorkouts=[
 {title:'胸部训练',calories:280,items:[{id:1,name:'杠铃卧推',sets:'4 × 8',weight:35,reps:8},{id:2,name:'哑铃上斜卧推',sets:'3 × 10',weight:12,reps:10},{id:3,name:'俯卧撑',sets:'3 × 12',weight:0,reps:12},{id:4,name:'绳索夹胸',sets:'3 × 12',weight:15,reps:12}]},
 {title:'背部训练',calories:300,items:[{id:5,name:'高位下拉',sets:'4 × 12',weight:30,reps:12},{id:6,name:'杠铃俯身划船',sets:'4 × 10',weight:30,reps:10},{id:7,name:'坐姿划船',sets:'3 × 12',weight:25,reps:12},{id:8,name:'单臂哑铃划船',sets:'3 × 10',weight:14,reps:10}]},
 {title:'主动恢复日',calories:120,rest:true,items:[{id:9,name:'轻松快走',sets:'1 × 20分钟',weight:0,reps:20},{id:10,name:'髋部动态拉伸',sets:'2 × 8',weight:0,reps:8},{id:11,name:'胸椎旋转',sets:'2 × 8',weight:0,reps:8}]},
 {title:'腿部训练',calories:360,items:[{id:12,name:'高脚杯深蹲',sets:'4 × 10',weight:16,reps:10},{id:13,name:'罗马尼亚硬拉',sets:'4 × 10',weight:16,reps:10},{id:14,name:'保加利亚分腿蹲',sets:'3 × 10',weight:8,reps:10},{id:15,name:'站姿提踵',sets:'3 × 15',weight:12,reps:15}]},
 {title:'肩部训练',calories:250,items:[{id:16,name:'哑铃肩推',sets:'4 × 10',weight:10,reps:10},{id:17,name:'哑铃侧平举',sets:'3 × 12',weight:5,reps:12},{id:18,name:'俯身反向飞鸟',sets:'3 × 12',weight:4,reps:12},{id:19,name:'绳索面拉',sets:'3 × 15',weight:15,reps:15}]},
 {title:'手臂与核心',calories:240,items:[{id:20,name:'哑铃弯举',sets:'3 × 12',weight:8,reps:12},{id:21,name:'绳索下压',sets:'3 × 12',weight:18,reps:12},{id:22,name:'锤式弯举',sets:'3 × 10',weight:8,reps:10},{id:23,name:'平板支撑',sets:'3 × 40秒',weight:0,reps:40}]},
 {title:'完全休息日',calories:0,rest:true,items:[]}
];
let workout=weeklyWorkouts[0].items;
state.completedByDay={0:new Set(weeklyWorkouts[0].items.map(x=>x.id)),1:new Set(weeklyWorkouts[1].items.map(x=>x.id)),3:new Set(weeklyWorkouts[3].items.map(x=>x.id)),4:new Set()};
state.completed=state.completedByDay[0];
const weeklyMeals=[
 [{type:'早餐',name:'燕麦香蕉坚果碗',emoji:'🥣',kcal:430,macro:'蛋白质 22g · 10分钟'},{type:'午餐',name:'黑椒鸡胸糙米饭',emoji:'🍛',kcal:590,macro:'蛋白质 46g · 25分钟'},{type:'晚餐',name:'番茄豆腐牛肉汤',emoji:'🍲',kcal:395,macro:'蛋白质 38g · 30分钟'}],
 [{type:'早餐',name:'鸡蛋蔬菜全麦卷',emoji:'🌯',kcal:410,macro:'蛋白质 27g · 15分钟'},{type:'午餐',name:'清蒸鲈鱼杂粮饭',emoji:'🐟',kcal:560,macro:'蛋白质 43g · 30分钟'},{type:'晚餐',name:'香菇鸡肉烩蔬菜',emoji:'🥘',kcal:430,macro:'蛋白质 40g · 25分钟'}],
 [{type:'早餐',name:'无糖酸奶水果杯',emoji:'🥛',kcal:380,macro:'蛋白质 24g · 5分钟'},{type:'午餐',name:'番茄牛肉意面',emoji:'🍝',kcal:610,macro:'蛋白质 42g · 25分钟'},{type:'晚餐',name:'虾仁豆腐蒸蛋',emoji:'🍤',kcal:390,macro:'蛋白质 36g · 20分钟'}],
 [{type:'早餐',name:'紫薯鸡蛋牛奶',emoji:'🍠',kcal:420,macro:'蛋白质 26g · 12分钟'},{type:'午餐',name:'照烧鸡腿藜麦饭',emoji:'🍱',kcal:630,macro:'蛋白质 45g · 30分钟'},{type:'晚餐',name:'冬瓜瘦肉菌菇汤',emoji:'🍲',kcal:370,macro:'蛋白质 34g · 25分钟'}],
 [{type:'早餐',name:'牛油果鸡蛋吐司',emoji:'🥑',kcal:450,macro:'蛋白质 25g · 10分钟'},{type:'午餐',name:'青椒牛肉荞麦面',emoji:'🍜',kcal:600,macro:'蛋白质 44g · 20分钟'},{type:'晚餐',name:'烤三文鱼时蔬',emoji:'🐟',kcal:440,macro:'蛋白质 39g · 25分钟'}],
 [{type:'早餐',name:'南瓜小米粥配鸡蛋',emoji:'🥚',kcal:390,macro:'蛋白质 23g · 20分钟'},{type:'午餐',name:'咖喱鸡胸土豆饭',emoji:'🍛',kcal:620,macro:'蛋白质 47g · 30分钟'},{type:'晚餐',name:'芹菜虾仁炒豆干',emoji:'🍤',kcal:400,macro:'蛋白质 37g · 20分钟'}],
 [{type:'早餐',name:'全麦三明治配豆浆',emoji:'🥪',kcal:440,macro:'蛋白质 28g · 12分钟'},{type:'午餐',name:'家常番茄炖牛腩',emoji:'🥘',kcal:650,macro:'蛋白质 48g · 40分钟'},{type:'晚餐',name:'鸡丝荞麦凉面',emoji:'🍜',kcal:410,macro:'蛋白质 35g · 20分钟'}]
];
let meals=weeklyMeals[0].map(x=>({...x}));
const gymPlans=[['新手全身','每周 2–3 天','全身主要肌群'],['上下肢二分化','每周 4 天','恢复与容量均衡'],['推拉腿三分化','每周 3–6 天','动作分类清晰'],['四分化进阶','每周 4 天','更多单肌群容量']];
const homePlans=[['徒手全身循环','20–30 分钟','无需器械'],['哑铃力量基础','30–40 分钟','一对哑铃'],['核心与体态','15–20 分钟','低冲击'],['低冲击燃脂','20 分钟','适合大体重新手']];

function navigate(target){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===target));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.target===target));document.getElementById('pageTitle').textContent=titles[target];window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.target)));
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.open).showModal()));
document.getElementById('notifyBtn').onclick=()=>toast('今天 19:00 · 上肢推力训练');
document.getElementById('todayLabel').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
const homeStats=(()=>{try{return JSON.parse(localStorage.getItem('fitnessHomeStats'))||{};}catch{return {};}})();
const burnInput=document.getElementById('todayBurnInput'),durationInput=document.getElementById('todayDurationInput');
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
burnInput.value=homeStats.burn??280;durationInput.value=homeStats.duration??45;let trainingDays=homeStats.trainingDays??6;
homeStats.daily=homeStats.daily||{};const todayKey=localDateKey();
if(!Object.keys(homeStats.daily).length){const samples=[[0,280,45],[1,0,0],[2,320,50],[3,260,40],[4,0,0],[5,410,65],[6,300,55]];samples.forEach(([offset,burn,duration])=>{const date=new Date();date.setDate(date.getDate()-offset);homeStats.daily[localDateKey(date)]={burn,duration};});}
if(!Array.isArray(homeStats.checkins)){homeStats.checkins=[];const offsets=[1,2,4,6,8,10,12,15,18,21];for(let i=0;i<Math.min(trainingDays,offsets.length);i++){const date=new Date();date.setDate(date.getDate()-offsets[i]);homeStats.checkins.push(localDateKey(date));}if(homeStats.lastCheckin&&!homeStats.checkins.includes(homeStats.lastCheckin))homeStats.checkins.push(homeStats.lastCheckin);}
function saveHomeStats(){homeStats.burn=+burnInput.value||0;homeStats.duration=+durationInput.value||0;homeStats.trainingDays=trainingDays;homeStats.daily[todayKey]={burn:homeStats.burn,duration:homeStats.duration};try{localStorage.setItem('fitnessHomeStats',JSON.stringify(homeStats));}catch{}}
let calendarView=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function renderCalendar(){const y=calendarView.getFullYear(),m=calendarView.getMonth(),today=new Date(),days=new Date(y,m+1,0).getDate(),offset=(new Date(y,m,1).getDay()+6)%7;document.getElementById('calendarTitle').textContent=`${y}年${m+1}月`;let html='<span class="calendar-blank"></span>'.repeat(offset);for(let day=1;day<=days;day++){const date=new Date(y,m,day),key=localDateKey(date),checked=homeStats.checkins.includes(key),future=date>new Date(today.getFullYear(),today.getMonth(),today.getDate()),isToday=key===todayKey;html+=`<span class="calendar-day ${checked?'checked':future?'future':'missed'} ${isToday?'today':''}"><b>${day}</b><i>${checked?'✓':future?'':'·'}</i></span>`;}document.getElementById('checkinCalendar').innerHTML=html;}
function renderCheckin(){const checked=homeStats.checkins.includes(todayKey);document.getElementById('trainingDays').textContent=trainingDays;document.getElementById('checkinTotal').textContent=trainingDays;document.getElementById('checkinDate').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});document.getElementById('checkinStatus').textContent=checked?'今日训练已签到':'今天还未签到';document.getElementById('checkinButton').textContent=checked?'今日已签到 ✓':'今日签到';document.getElementById('checkinButton').disabled=checked;renderCalendar();}
function weekDateKeys(){const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));return Array.from({length:7},(_,i)=>{const date=new Date(monday);date.setDate(monday.getDate()+i);return localDateKey(date);});}
function openStatHistory(type){saveHomeStats();const isBurn=type==='burn',unit=isBurn?'千卡':'分钟',keys=weekDateKeys(),values=keys.map(key=>homeStats.daily[key]?.[type]||0),monthPrefix=todayKey.slice(0,7),weekTotal=values.reduce((a,b)=>a+b,0),monthTotal=Object.entries(homeStats.daily).filter(([key])=>key.startsWith(monthPrefix)).reduce((sum,[,value])=>sum+(value[type]||0),0),max=Math.max(...values,1);document.getElementById('statHistoryTitle').textContent=isBurn?'消耗记录':'训练时长记录';document.getElementById('weekStatTotal').textContent=weekTotal.toLocaleString();document.getElementById('monthStatTotal').textContent=monthTotal.toLocaleString();document.getElementById('weekStatUnit').textContent=unit;document.getElementById('monthStatUnit').textContent=unit;document.getElementById('statHistoryBars').innerHTML=values.map((value,i)=>`<div><em>${value||'-'}</em><i><b style="height:${value?Math.max(8,value/max*72):3}px"></b></i><span>${'一二三四五六日'[i]}</span></div>`).join('');document.getElementById('statHistoryList').innerHTML=keys.map((key,i)=>`<div><span>周${'一二三四五六日'[i]} · ${key.slice(5).replace('-','/')}</span><b>${values[i]} ${unit}</b></div>`).join('');document.getElementById('statHistoryModal').showModal();}
[burnInput,durationInput].forEach(input=>{input.addEventListener('input',saveHomeStats);input.addEventListener('change',()=>toast('今日训练数据已保存'));});
document.getElementById('openBurnHistory').onclick=()=>openStatHistory('burn');document.getElementById('openDurationHistory').onclick=()=>openStatHistory('duration');document.getElementById('closeStatHistory').onclick=()=>document.getElementById('statHistoryModal').close();
document.getElementById('openCheckin').onclick=()=>{calendarView=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderCheckin();document.getElementById('checkinModal').showModal();};document.getElementById('closeCheckin').onclick=()=>document.getElementById('checkinModal').close();document.getElementById('calendarPrev').onclick=()=>{calendarView.setMonth(calendarView.getMonth()-1);renderCalendar();};document.getElementById('calendarNext').onclick=()=>{calendarView.setMonth(calendarView.getMonth()+1);renderCalendar();};document.getElementById('checkinButton').onclick=()=>{if(homeStats.checkins.includes(todayKey))return;homeStats.checkins.push(todayKey);homeStats.lastCheckin=todayKey;trainingDays+=1;saveHomeStats();renderCheckin();toast('签到成功，训练天数 +1');};saveHomeStats();renderCheckin();

document.getElementById('foodCalculate').onclick=()=>{const per100=+document.getElementById('foodCalories').value||0;const weight=+document.getElementById('foodWeight').value||0;const result=Math.round(per100*weight/100);document.getElementById('foodResult').textContent=result+' 千卡';document.getElementById('riceBowls').textContent=(result/230).toFixed(1)+' 碗米饭';toast('热量计算完成');};

const featureModal=document.getElementById('featureModal');
function showFeature(title,html,confirm='完成'){document.getElementById('featureTitle').textContent=title;document.getElementById('featureContent').innerHTML=`<div class="feature-content">${html}</div>`;document.getElementById('confirmFeature').textContent=confirm;featureModal.showModal();}
document.getElementById('closeFeature').onclick=()=>featureModal.close();document.getElementById('confirmFeature').onclick=()=>featureModal.close();
document.getElementById('calorieHelp').onclick=()=>showFeature('食物热量计算器怎么用',`<p>这个工具用于计算<b>你实际吃下的一份食物</b>大约含有多少热量。</p><ol><li>查看食品包装、食谱或可靠食物数据库，填写“每 100 克热量”。</li><li>称量准备食用的重量，填写“食物重量”。</li><li>点击“立即计算”，系统会按下面的公式得出结果。</li></ol><strong>热量 = 每100克热量 × 食物重量 ÷ 100</strong><p><b>示例：</b>燕麦每 100 克约 389 千卡，吃 50 克，结果约为 195 千卡。</p><p>烹调油、酱料和饮料也会产生热量，应单独计算后相加。这里计算的是食物热量，不是你的每日建议摄入量；每日目标请结合基础代谢和活动量查看。</p>`,'我知道了');

document.querySelector('.tool-grid button:nth-child(8)').onclick=()=>showFeature('热量单位换算','<p>常用换算关系：</p><strong>1 千卡 = 4.184 千焦</strong><p>例如：500 千卡约等于 2,092 千焦。</p>');
let activeHealthTool='bmi';
const healthModal=document.getElementById('healthModal');
const healthTitles={bmi:'BMI 计算',bodyfat:'体脂率估算',bmr:'分年龄基础代谢',weight:'体重管理'};
function baseHealthFields(){const p=state.profile;return `<div class="field-row"><label>年龄<input name="age" type="number" min="14" max="55" value="${p.age}" required></label><label>性别<select name="sex"><option value="male" ${p.sex==='male'?'selected':''}>男</option><option value="female" ${p.sex==='female'?'selected':''}>女</option></select></label></div><div class="field-row"><label>身高（cm）<input name="height" type="number" min="130" max="220" value="${p.height}" required></label><label>体重（kg）<input name="weight" type="number" min="35" max="250" step="0.1" value="${p.weight}" required></label></div>`;}
function openHealthTool(tool){activeHealthTool=tool;document.getElementById('healthToolTitle').textContent=healthTitles[tool];let fields=baseHealthFields();if(tool==='bodyfat')fields+=`<div class="field-row"><label>腰围（cm）<input name="waist" type="number" min="40" max="200" step="0.1" value="82" required></label><label>颈围（cm）<input name="neck" type="number" min="20" max="80" step="0.1" value="37" required></label></div><label>臀围（cm，仅女性公式使用）<input name="hip" type="number" min="50" max="200" step="0.1" value="96"></label><div class="health-tool-note">在自然呼气末测量腰围，软尺贴合但不要勒紧。围度法只能提供估算，不能代替专业人体成分检测。</div>`;else if(tool==='bmr')fields+=`<label>日常活动量<select name="activity"><option value="1.2">久坐为主</option><option value="1.375" selected>轻度活动</option><option value="1.55">中度活动</option><option value="1.725">高度活动</option></select></label><div class="health-tool-note">14–18 岁使用 Schofield 青少年估算；19–55 岁使用 Mifflin–St Jeor 成人估算。结果均为静息能量估算值。</div>`;else if(tool==='bmi')fields+=`<div class="health-tool-note">18 岁以上按中国成人标准解释；14–17 岁需要结合年龄、月份和性别的 BMI 百分位，本工具不会用成人阈值给青少年贴标签。</div>`;else fields+=`<label>管理目标<select name="goal"><option value="lose">减脂</option><option value="keep">保持体重</option><option value="gain">增肌</option></select></label><label>日常活动量<select name="activity"><option value="1.2">久坐为主</option><option value="1.375" selected>轻度活动</option><option value="1.55">中度活动</option><option value="1.725">高度活动</option></select></label><div class="health-tool-note">体重管理同时参考 BMI、能量估算和目标；青少年不自动生成减重热量目标。</div>`;document.getElementById('healthToolFields').innerHTML=fields;document.getElementById('healthToolResult').classList.remove('show');healthModal.showModal();}
document.querySelectorAll('[data-health-tool]').forEach(b=>b.onclick=()=>openHealthTool(b.dataset.healthTool));document.getElementById('closeHealth').onclick=()=>healthModal.close();
document.getElementById('healthToolForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),age=+f.get('age'),height=+f.get('height'),weight=+f.get('weight'),sex=f.get('sex'),bmi=weight/Math.pow(height/100,2);let html='';if(activeHealthTool==='bmi'){let category=age<18?'青少年需按年龄/性别百分位评估':bmi<18.5?'体重偏低':bmi<24?'正常范围':bmi<28?'超重范围':'肥胖范围';html=`<h3>你的 BMI</h3><strong>${bmi.toFixed(1)}</strong><p>${category}</p>${age<18?'<p class="warning">14–17 岁不能直接使用成人 BMI 分类，请结合生长曲线并咨询监护人、校医或医生。</p>':'<div class="result-grid"><div>中国成人正常范围<b>18.5–23.9</b></div><div>当前体重状态<b>'+category+'</b></div></div>'}`;}else if(activeHealthTool==='bodyfat'){if(age<18){html='<h3>暂不提供青少年体脂率判定</h3><p class="warning">青春期身体组成变化较大，建议使用专业设备并由医生或合格教练解释结果。</p>';}else{const waist=+f.get('waist')/2.54,neck=+f.get('neck')/2.54,hip=+f.get('hip')/2.54,h=height/2.54;let bf=sex==='male'?86.010*Math.log10(waist-neck)-70.041*Math.log10(h)+36.76:163.205*Math.log10(waist+hip-neck)-97.684*Math.log10(h)-78.387;if(!isFinite(bf)||bf<2||bf>65){html='<h3>请检查围度数据</h3><p class="warning">腰围必须大于颈围，女性还需要填写有效臀围。</p>';}else{const range=sex==='male'?(bf<6?'偏低':bf<25?'一般健康区间':'偏高'):(bf<14?'偏低':bf<32?'一般健康区间':'偏高');html=`<h3>估算体脂率</h3><strong>${bf.toFixed(1)}%</strong><p>${range}</p><p>围度公式对个体可能有数个百分点误差，请观察长期趋势，不要把单次结果当作诊断。</p>`;}}}else if(activeHealthTool==='bmr'){const bmr=age<=18?(sex==='male'?17.686*weight+658.2:13.384*weight+692.6):(10*weight+6.25*height-5*age+(sex==='male'?5:-161));const tdee=bmr*(+f.get('activity'));html=`<h3>估算基础代谢</h3><strong>${Math.round(bmr)} kcal/天</strong><div class="result-grid"><div>年龄公式<b>${age<=18?'Schofield 青少年':'Mifflin–St Jeor 成人'}</b></div><div>估算维持热量<b>${Math.round(tdee)} kcal/天</b></div></div><p>基础代谢不是建议摄入量；维持热量还会受到训练、步数、睡眠和个体差异影响。</p>`;}else{if(age<18){html='<h3>青少年成长优先</h3><p class="warning">不自动生成减重热量缺口或目标体重。应保证生长发育、规律进食和适龄运动，需要调整体重时由监护人与专业人员共同制定方案。</p>';}else{const bmr=10*weight+6.25*height-5*age+(sex==='male'?5:-161),tdee=bmr*(+f.get('activity')),goal=f.get('goal'),targetCalories=Math.round(tdee+(goal==='lose'?-300:goal==='gain'?250:0)),minW=18.5*Math.pow(height/100,2),maxW=23.9*Math.pow(height/100,2);html=`<h3>体重管理建议</h3><strong>${targetCalories} kcal/天</strong><div class="result-grid"><div>当前 BMI<b>${bmi.toFixed(1)}</b></div><div>成人参考体重范围<b>${minW.toFixed(1)}–${maxW.toFixed(1)} kg</b></div><div>估算维持热量<b>${Math.round(tdee)} kcal</b></div><div>目标调整<b>${goal==='lose'?'温和缺口 300 kcal':goal==='gain'?'温和盈余 250 kcal':'维持平衡'}</b></div></div><p>建议每 2–3 周根据体重趋势、围度、训练表现和饥饿感调整，而不是每天追逐体重波动。</p>`;}}document.getElementById('healthToolResult').innerHTML=html;document.getElementById('healthToolResult').classList.add('show');};
document.querySelectorAll('.recommend-row button').forEach((button,index)=>button.onclick=()=>{const parts=['背','胸','腿'];state.filter=parts[index];document.querySelectorAll('#exerciseFilters button').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));renderExercises();navigate('exercise');toast('已打开'+parts[index]+'部动作');});

document.getElementById('goalSlider').addEventListener('click',e=>{const card=e.target.closest('.goal-card');if(!card)return;state.goal=card.dataset.goal;document.querySelectorAll('.goal-card').forEach(x=>x.classList.toggle('selected',x===card));calculate();});
document.querySelector('.part-pills').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.part-pills button').forEach(x=>x.classList.toggle('active',x===b));toast('已选择'+b.textContent+'部训练');};
function calculate(){const p=state.profile;let bmr=10*p.weight+6.25*p.height-5*p.age+(p.sex==='male'?5:-161);const maintenance=Math.round(bmr*p.activity/10)*10;const delta=state.goal==='lose'?-300:state.goal==='gain'?250:0;document.getElementById('targetCalories').innerHTML=`${Math.round(bmr).toLocaleString()}`;document.getElementById('profileWeight').innerHTML=`${p.weight.toFixed(1)}<small> kg</small>`;}

function tabControl(parent,selector,key){document.getElementById(parent).addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll(`#${parent} button`).forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll(selector).forEach(x=>x.classList.toggle('active',x.dataset[key]===b.dataset.panel));});}
tabControl('trainingTabs','.training-panel','training');
document.getElementById('dietTabs').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#dietTabs button').forEach(x=>x.classList.toggle('active',x===b));toast(b.textContent+'方案已切换');};

function renderWorkout(){document.getElementById('workoutList').innerHTML=workout.length?workout.map((w,i)=>`<article class="workout-item ${state.completed.has(w.id)?'done':''}" data-id="${w.id}"><div class="exercise-icon">${i+1}</div><div class="workout-copy"><button class="workout-link" type="button" data-workout-name="${w.name}"><b>${w.name}</b><small>查看动作示范 ›</small></button><p>${w.sets} · ${w.weight===0?'按舒适节奏完成':'组间休息 90 秒'}</p><div class="set-inputs"><input type="number" value="${w.weight}" aria-label="重量"><input type="number" value="${w.reps}" aria-label="次数"><span class="muted">${w.weight===0?'分钟/次':'kg / 次'}</span></div></div><button class="done-button">✓</button></article>`).join(''):'<div class="feature-content"><strong>今天完全休息</strong><p>保证充足睡眠与正常饮食。轻松散步即可，不需要额外安排力量或有氧训练。</p></div>';updateVolume();}
document.getElementById('workoutList').onclick=e=>{const link=e.target.closest('.workout-link');if(link){openWorkoutExercise(link.dataset.workoutName);return;}const btn=e.target.closest('.done-button');if(!btn)return;const id=+btn.closest('.workout-item').dataset.id;state.completed.has(id)?state.completed.delete(id):state.completed.add(id);renderWorkout();toast(state.completed.has(id)?'动作已完成':'已取消完成');};
document.getElementById('workoutList').oninput=updateVolume;
function itemVolume(item){return (item.weight||0)*(item.reps||0)*(parseInt(item.sets)||0)}
function previousExerciseVolume(item,index){const factors=[.94,.96,.92,.95];return Math.max(1,Math.round(itemVolume(item)*factors[index%factors.length]/10)*10);}
function updateExerciseCapacity(){const list=document.getElementById('exerciseCapacityList');if(!workout.length){list.innerHTML='<div class="capacity-empty">休息日没有负重容量目标，恢复也是训练计划的一部分。</div>';document.getElementById('capacityAdvice').textContent='今天优先保证睡眠、饮食和轻松活动，不需要为了数字额外加练。';return;}list.innerHTML=workout.map((item,index)=>{const done=state.completed.has(item.id),sets=parseInt(item.sets)||0;if(item.weight===0){const lastReps=Math.max(1,item.reps-2),nextReps=done?item.reps+2:item.reps;return `<article class="exercise-capacity-row ${done?'is-done':'is-pending'}"><button class="capacity-name" type="button" data-workout-name="${item.name}"><b>${item.name}</b><small>${sets} 组 · 次数/时间型 ›</small></button><div class="capacity-metric"><span>上次</span><b>${sets}×${lastReps}</b></div><div class="capacity-metric"><span>本次</span><b>${done?sets+'×'+item.reps:'待完成'}</b><em>${done?'已记录':'按计划'}</em></div><div class="capacity-metric target"><span>下次目标</span><b>${sets}×${nextReps}</b><em>${done?'+2 次/秒':'先完成本次'}</em></div></article>`;}const planned=itemVolume(item),previous=previousExerciseVolume(item,index),current=done?planned:0,change=done?((current-previous)/previous*100):0,next=done?Math.max(current+10,Math.round(current*1.03/10)*10):planned;return `<article class="exercise-capacity-row ${done?'is-done':'is-pending'}"><button class="capacity-name" type="button" data-workout-name="${item.name}"><b>${item.name}</b><small>${item.weight} kg × ${item.reps} 次 × ${sets} 组 ›</small></button><div class="capacity-metric"><span>上次</span><b>${previous.toLocaleString()}</b><em>kg</em></div><div class="capacity-metric"><span>本次</span><b>${done?current.toLocaleString():'待完成'}</b><em>${done?(change>=0?'+':'')+change.toFixed(1)+'%':'按计划'}</em></div><div class="capacity-metric target"><span>下次目标</span><b>${next.toLocaleString()}</b><em>kg</em></div></article>`;}).join('');const completed=workout.filter(item=>state.completed.has(item.id)).length;document.getElementById('capacityAdvice').textContent=completed===workout.length?'这些目标已按每个动作分别计算。仅在动作标准、目标次数完成且恢复良好时，下一次再小幅增加重量或次数；不必每次都强行加重。':`已完成 ${completed}/${workout.length} 个动作。未完成的动作先按本次计划执行，完成后才会生成它自己的下一次容量目标。`;}
document.getElementById('exerciseCapacityList').onclick=e=>{const link=e.target.closest('[data-workout-name]');if(link)openWorkoutExercise(link.dataset.workoutName);};
function updateVolume(){let total=0;document.querySelectorAll('.workout-item').forEach((el,i)=>{const inputs=el.querySelectorAll('input');workout[i].weight=+inputs[0].value||0;workout[i].reps=+inputs[1].value||0;if(state.completed.has(+el.dataset.id))total+=itemVolume(workout[i])});document.getElementById('totalVolume').textContent=total.toLocaleString()+' kg';document.getElementById('exerciseProgress').textContent=`${state.completed.size} / ${workout.length}`;updateExerciseCapacity();}

function renderPlans(id,data){document.getElementById(id).innerHTML=data.map(p=>`<article class="plan-card"><i></i><b>${p[0]}</b><p>${p[1]}<br>${p[2]}</p><span>查看计划 →</span></article>`).join('');}
renderPlans('gymPlans',gymPlans);renderPlans('homePlans',homePlans);document.querySelector('.equipment-choice').onclick=e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('.equipment-choice button').forEach(x=>x.classList.toggle('selected',x===e.target));toast('已切换为'+e.target.textContent+'计划');};
document.querySelector('.workout-table .plain').onclick=()=>showFeature('编辑今日计划','<p>当前计划包含 4 个动作。正式小程序中可在这里拖动排序、修改组数次数，或从动作库添加新动作。</p><ul><li>杠铃卧推 4 × 8</li><li>哑铃肩推 3 × 10</li><li>哑铃侧平举 3 × 12</li><li>绳索下压 3 × 12</li></ul>','保存计划');
document.querySelector('.week-card .primary').onclick=()=>{showFeature('计划已生成','<p>已根据“增肌、新手、每周 4 次”的偏好生成计划。</p><strong>上肢 / 下肢二分化</strong><p>建议连续执行 4 周，每周根据完成情况小幅增加次数或重量。</p>','采用此计划');toast('专属计划生成完成');};
document.querySelectorAll('.week-row button').forEach(b=>b.onclick=()=>{const day=+b.dataset.day;document.querySelectorAll('.week-row button').forEach(x=>x.classList.remove('selected-demo'));b.classList.add('selected-demo');state.selectedTrainingDay=day;workout=weeklyWorkouts[day].items;if(!state.completedByDay[day])state.completedByDay[day]=new Set();state.completed=state.completedByDay[day];document.getElementById('workoutDayTitle').textContent=`周${'一二三四五六日'[day]}计划 · ${weeklyWorkouts[day].title}`;document.getElementById('workoutCalories').textContent=weeklyWorkouts[day].calories+' kcal';renderWorkout();document.querySelectorAll('#trainingTabs button').forEach((x,i)=>x.classList.toggle('active',i===0));document.querySelectorAll('.training-panel').forEach(x=>x.classList.toggle('active',x.dataset.training==='today'));toast('已切换到周'+'一二三四五六日'[day]+'计划');});
document.getElementById('capacityHelp').onclick=()=>showFeature('单动作容量如何计算','<p><b>每个动作分别计算：重量 × 每组次数 × 完成组数</b></p><p>例如罗马尼亚硬拉 16 kg × 10 次 × 4 组，本次容量为 640 kg，它只和上一次罗马尼亚硬拉比较，不与深蹲等其他动作相加。</p><p>徒手动作和静态支撑使用有效组数、次数或时间记录，不强行折算成公斤。只有动作标准、恢复良好时，下一次才小幅增加。</p>');

function renderExercises(){const term=document.getElementById('exerciseSearch').value.trim().toLowerCase();const typeOk=x=>state.exerciseType==='全部'||state.exerciseType==='新手友好'||(state.exerciseType==='徒手'&&x.equipment==='徒手')||(state.exerciseType==='器械'&&x.equipment!=='徒手')||state.exerciseType==='拉伸';const list=exercises.filter(x=>(state.filter==='全部'||x.part===state.filter)&&(state.equipment==='全部'||x.equipment===state.equipment)&&typeOk(x)&&(!term||(x.name+(x.englishName||'')+x.target+x.part).toLowerCase().includes(term))),visible=list.slice(0,state.exerciseLimit),more=list.length-visible.length;document.getElementById('exerciseCount').textContent=list.length;document.getElementById('exerciseList').innerHTML=visible.map(x=>`<button class="exercise-card" data-id="${x.id}"><div class="exercise-visual">${x.image?`<img src="${x.image}" alt="${x.name}" loading="lazy">`:x.icon}</div><div class="exercise-info"><h4>${x.name}</h4><p>目标：${x.target}</p><div class="chips"><span>${x.part}</span><span>${x.equipment}</span></div></div><span class="open">›</span></button>`).join('')+(more?`<button class="exercise-load-more" type="button">再加载 ${Math.min(60,more)} 个<small>当前显示 ${visible.length} / ${list.length}</small></button>`:'')||'<div class="feature-content"><b>暂无匹配动作</b><p>试试切换部位、器械或关键词。</p></div>';}
document.getElementById('exerciseFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.filter=b.dataset.filter;state.exerciseLimit=60;document.querySelectorAll('#exerciseFilters button').forEach(x=>x.classList.toggle('active',x===b));renderExercises();};document.getElementById('exerciseSearch').oninput=()=>{state.exerciseLimit=60;renderExercises();};
document.querySelector('.type-row').onclick=e=>{const b=e.target.closest('button');if(!b)return;state.exerciseType=b.textContent.trim();state.exerciseLimit=60;document.querySelectorAll('.type-row button').forEach(x=>x.classList.toggle('active',x===b));if(state.exerciseType==='拉伸')showFeature('拉伸动作库','<p>拉伸专题将在完整动作数据导入后展示。</p><ul><li>训练前动态热身</li><li>训练后静态拉伸</li><li>办公久坐舒缓</li></ul>');renderExercises();};
document.querySelector('.subfilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.subfilters button').forEach(x=>x.classList.toggle('active',x===b));toast('已切换到'+b.textContent);};
const equipment=['全部','徒手','哑铃','杠铃','器械'];document.getElementById('equipmentBtn').onclick=()=>{state.equipment=equipment[(equipment.indexOf(state.equipment)+1)%equipment.length];state.exerciseLimit=60;document.getElementById('equipmentBtn').textContent='器械：'+state.equipment+'⌄';renderExercises();};
function exerciseCredit(x){if(x.sourceUrl)return `动画：${x.author||'Wikimedia Commons 贡献者'} · <a href="${x.licenseUrl}" target="_blank" rel="noopener">${x.license}</a> · <a href="${x.sourceUrl}" target="_blank" rel="noopener">查看原始文件</a> · 未修改`;return `${x.attribution||'原型使用自制示意图'}<br>仅限内部原型验证；正式公开前需另行确认媒体授权。`;}
function openExerciseDetail(x){if(!x)return;document.getElementById('exerciseDetail').innerHTML=`<div class="exercise-detail-head"><div><span class="eyebrow">${x.part} · ${x.equipment}</span><h2>${x.name}</h2><p class="detail-meta">${x.englishName||''} · 主要目标：${x.target}</p></div></div><div class="detail-figure">${x.gif?`<img src="${x.gif}" alt="${x.name}动作演示">`:x.icon}</div><details class="steps-disclosure"><summary>查看动作步骤 <span>⌄</span></summary><ol>${x.steps.map(s=>`<li>${s}</li>`).join('')}</ol></details><p class="copyright">${exerciseCredit(x)}</p>`;document.getElementById('exerciseModal').showModal();}
function openWorkoutExercise(name){const libraryId=workoutLibraryMap[name],pool=exercises;const x=pool.find(item=>libraryId&&String(item.id).trim()===String(libraryId).trim())||pool.find(item=>item.name===name||item.name.includes(name)||name.includes(item.name));navigate('exercise');state.equipment='全部';state.exerciseType='全部';document.getElementById('exerciseSearch').value=x?'':name;document.querySelectorAll('.type-row button').forEach(button=>button.classList.toggle('active',button.textContent.trim()==='全部'));if(x){state.filter=x.part;document.querySelectorAll('#exerciseFilters button').forEach(button=>button.classList.toggle('active',button.dataset.filter===x.part));renderExercises();openExerciseDetail(x);toast(`已打开${x.name}动作示范`);}else{state.filter='全部';document.querySelectorAll('#exerciseFilters button').forEach(button=>button.classList.toggle('active',button.dataset.filter==='全部'));renderExercises();toast('动作库暂未导入这个动作，已为你搜索');}}
document.getElementById('exerciseList').onclick=e=>{if(e.target.closest('.exercise-load-more')){state.exerciseLimit+=60;renderExercises();return;}const card=e.target.closest('.exercise-card');if(!card)return;openExerciseDetail(exercises.find(a=>String(a.id)===card.dataset.id));};document.getElementById('closeExercise').onclick=()=>document.getElementById('exerciseModal').close();

function renderMeals(){document.getElementById('mealList').innerHTML=meals.map(x=>`<article class="meal-card"><div class="meal-visual">${x.emoji}</div><div><span class="meal-type">${x.type}</span><h4>${x.name}</h4><p>${x.macro}</p></div><div class="meal-kcal"><b>${x.kcal}</b><small>kcal</small></div></article>`).join('');}
renderMeals();
document.querySelector('.day-row').onclick=e=>{const b=e.target.closest('button');if(!b)return;const day=+b.dataset.day;document.querySelectorAll('.day-row button').forEach(x=>x.classList.toggle('active',x===b));meals=weeklyMeals[day].map(x=>({...x}));document.getElementById('mealDayTitle').textContent=`周${'一二三四五六日'[day]}食谱计划`;renderMeals();toast('已查看周'+'一二三四五六日'[day]+'食谱');};
document.querySelector('.diet-actions .primary').onclick=()=>showFeature('本周食谱已生成','<p>按当前减脂目标生成家常菜方案：</p><strong>每日约 2,080 千卡</strong><ul><li>蛋白质约 135g</li><li>三餐加一次健康加餐</li><li>食材可在同类中替换</li></ul>','采用此食谱');
document.querySelector('.diet-actions button:last-child').onclick=()=>{const first=meals.shift();meals.push(first);renderMeals();toast('已替换一组菜单');};

document.querySelector('.streak-card button').onclick=()=>showFeature('本月目标','<strong>完成 16 次训练</strong><p>当前已完成 8 次，连续打卡 12 天。本周还剩 1 次力量训练。</p>');
const profileFeatures={训练记录:'最近 4 周共完成 8 次训练，累计训练容量 18,640 kg。',饮食记录:'本周平均每日摄入 2,036 千卡，蛋白质完成率 86%。',收藏动作:'已收藏 6 个动作，可从动作库详情页继续添加。',体重管理:'当前 72.0 kg，本月下降 1.2 kg，目标体重 68.0 kg。',我的计划:'当前执行“上肢 / 下肢二分化”第 2 周。',目标管理:'当前目标为减脂塑形，可重新填写资料调整目标。',消息通知:'训练提醒：19:00；每日饮水提醒：已开启。',隐私与帮助:'个人资料仅用于生成训练与饮食建议。原型数据保存在当前浏览器中。'};
document.querySelectorAll('.settings-list button').forEach(b=>b.onclick=()=>{const title=b.querySelector('b').textContent;if(title==='目标管理'){document.getElementById('profileModal').showModal();return;}showFeature(title,`<p>${profileFeatures[title]}</p>`);});

document.getElementById('ageInput').oninput=e=>{const age=+e.target.value;const note=age<18?'14–17 岁：使用青少年安全模板，需监护人知情，不采用成人极端热量或负重规则。':age>=40?'40–55 岁：加强健康筛查、热身、恢复与渐进负荷。':'18–39 岁：采用常规新手训练与热量模板。';document.getElementById('ageNote').textContent=note;};
document.getElementById('profileForm').onsubmit=e=>{e.preventDefault();const risk=document.getElementById('riskInput').checked;if(risk){document.getElementById('ageNote').textContent='检测到健康风险项：暂不自动生成训练计划，请先咨询医生或专业教练。';document.getElementById('ageNote').style.borderColor='var(--red)';return;}state.profile={age:+ageInput.value,height:+heightInput.value,weight:+weightInput.value,sex:sexInput.value,activity:+activityInput.value};calculate();document.getElementById('profileModal').close();toast('资料已保存，方案已重新计算');};
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1800);}
renderWorkout();renderExercises();calculate();
